name: flutter_e_ticket
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0
  uuid: any
  image_picker_web: any
  qr_flutter: ^3.1.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
#  animations: ^1.1.2
#  google_fonts: ^1.1.2
#  email_auth: ^0.0.1+1.6
#  shared_preferences: ^0.5.12+4
#  adaptive_theme: ^1.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.11.5
#  integration_test:
#    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
